# Generated by Django 5.2.7 on 2026-03-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='CuentaPorPagar',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
